# Trigger on push
on:
  # File paths to consider in the event. Optional; defaults to all
  push:
    paths:
    - standalone/*
    - .github/workflows/*

env:
  CMSSW_VERSION: CMSSW_10_2_21  

name: Build Standalone
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Registry Login
      uses: actions-hub/docker@v1.0.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Standalone CMS
      env:
        BASE_IMAGE: clelange/cc7-cms:latest
        SCRAM_ARCH: slc7_amd64_gcc700
        CMSSW_VERSION: CMSSW_10_2_21
      run: export DOCKER_IMAGE="treemaker/cmssw" && make CMSSW_VERSION=${{ env.CMSSW_VERSION }} SCRAM_ARCH=${{ env.SCRAM_ARCH }} BASEIMAGE=${{ env.BASE_IMAGE }}
    - name: Explore Docker Images
      run: docker images -a
#    - name: Docker Tag Standalone CMS
#      if: success()
#      uses: actions-hub/docker@v1.0.0
#      with:
#        args: tag standalone treemaker/${{ env.CMSSW_VERSION }}
#    - name: Docker Push latest Standalone CMS
#      if: success()
#      uses: actions-hub/docker@v1.0.0
#      with:
#        args: push treemaker/${{ env.CMSSW_VERSION }}:latest
